In [2]:
#  Importing Dependencies

import os
import csv
import pandas as pd

In [ ]:
#  Linking in csv files sources using the OS Module

csvpath_2015 = os.path.join('Resources', '2015.csv')
csvpath_2016 = os.path.join('Resources', '2016.csv')
csvpath_2017 = os.path.join('Resources', '2017.csv')
csvpath_2018 = os.path.join('Resources', '2018.csv')
csvpath_2019 = os.path.join('Resources', '2019.csv')

In [37]:
#  Loading CSV Data from data files using CSV Module .read_csv Method

csv_2015 = pd.read_csv(csvpath_2015)
csv_2016 = pd.read_csv(csvpath_2016)
csv_2017 = pd.read_csv(csvpath_2017)
csv_2018 = pd.read_csv(csvpath_2018)
csv_2019 = pd.read_csv(csvpath_2019)

In [ ]:
#  Creating new dataframes for the five underlying datasets, insuring column structure and 
#  naming conventions are congruent.  Also drops unnecessary columns some datasets include.  Also
#  adding a year column for later grouped analysis calcs.

In [47]:
csv_2019_restructured = csv_2019
csv_2019_restructured["Year"] = 2019
csv_2019_restructured.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Year
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,2019
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,2019
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,2019
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,2019
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298,2019

In [48]:
csv_2018_restructured = csv_2018
csv_2018_restructured["Year"] = 2018
csv_2018_restructured.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Year
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393,2018
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340,2018
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408,2018
3,4,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138,2018
4,5,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357,2018

In [44]:
# 2019 & 2018 datasets are the same in structure & column naming convention.  Restructure / Rename
# datasets from 2015 - 2017.

# Convert / Fix 2017 Data

csv_2017_restructured = csv_2017[["Happiness.Rank",
                                  "Country",
                                  "Happiness.Score",
                                  "Economy..GDP.per.Capita.",
                                  "Family",
                                  "Health..Life.Expectancy.",
                                  "Freedom",
                                  "Generosity",
                                  "Trust..Government.Corruption."]]

csv_2017_restructured = csv_2017_restructured.rename(columns={"Happiness.Rank": "Overall rank",
                                      "Country": "Country or region",
                                      "Happiness.Score": "Score",
                                      "Economy..GDP.per.Capita.": "GDP per capita",
                                      "Family": "Social support",
                                      "Health..Life.Expectancy.": "Healthy life expectancy",
                                      "Freedom": "Freedom to make life choices",
                                      "Generosity": "Generosity",
                                      "Trust..Government.Corruption.": "Perceptions of corruption"})
csv_2017_restructured["Year"] = 2017
csv_2017_restructured.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Year
0,1,Norway,7.537,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2017
1,2,Denmark,7.522,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2017
2,3,Iceland,7.504,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2017
3,4,Switzerland,7.494,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2017
4,5,Finland,7.469,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2017

In [43]:
# 2019 & 2018 datasets are the same in structure & column naming convention.  Restructure / Rename
# datasets from 2015 - 2017.

# Convert / fix 2016 Data

csv_2016_restructured = csv_2016[["Happiness Rank",
                                 "Country",
                                  "Happiness Score",
                                  "Economy (GDP per Capita)",
                                  "Family",
                                  "Health (Life Expectancy)",
                                  "Freedom",
                                  "Generosity",
                                  "Trust (Government Corruption)"]]

csv_2016_restructured = csv_2016_restructured.rename(columns={"Happiness Rank": "Overall rank",
                                      "Country": "Country or region",
                                      "Happiness Score": "Score",
                                      "Economy (GDP per Capita)": "GDP per capita",
                                      "Family": "Social support",
                                      "Health (Life Expectancy)": "Healthy life expectancy",
                                      "Freedom": "Freedom to make life choices",
                                      "Generosity": "Generosity",
                                      "Trust (Government Corruption)": "Perceptions of corruption"})
csv_2016_restructured["Year"] = 2016
csv_2016_restructured.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Year
0,1,Denmark,7.526,1.44178,1.16374,0.79504,0.57941,0.36171,0.44453,2016
1,2,Switzerland,7.509,1.52733,1.14524,0.86303,0.58557,0.28083,0.41203,2016
2,3,Iceland,7.501,1.42666,1.18326,0.86733,0.56624,0.47678,0.14975,2016
3,4,Norway,7.498,1.57744,1.12690,0.79579,0.59609,0.37895,0.35776,2016
4,5,Finland,7.413,1.40598,1.13464,0.81091,0.57104,0.25492,0.41004,2016

In [42]:
# 2019 & 2018 datasets are the same in structure & column naming convention.  Restructure / Rename
# datasets from 2015 - 2017.

# Convert / fix 2015 Data

csv_2015_restructured = csv_2015[["Happiness Rank",
                                 "Country",
                                  "Happiness Score",
                                  "Economy (GDP per Capita)",
                                  "Family",
                                  "Health (Life Expectancy)",
                                  "Freedom",
                                  "Generosity",
                                  "Trust (Government Corruption)"]]

csv_2015_restructured = csv_2015_restructured.rename(columns={"Happiness Rank": "Overall rank",
                                      "Country": "Country or region",
                                      "Happiness Score": "Score",
                                      "Economy (GDP per Capita)": "GDP per capita",
                                      "Family": "Social support",
                                      "Health (Life Expectancy)": "Healthy life expectancy",
                                      "Freedom": "Freedom to make life choices",
                                      "Generosity": "Generosity",
                                      "Trust (Government Corruption)": "Perceptions of corruption"})
csv_2015_restructured["Year"] = 2015
csv_2015_restructured.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Year
0,1,Switzerland,7.587,1.39651,1.34951,0.94143,0.66557,0.29678,0.41978,2015
1,2,Iceland,7.561,1.30232,1.40223,0.94784,0.62877,0.43630,0.14145,2015
2,3,Denmark,7.527,1.32548,1.36058,0.87464,0.64938,0.34139,0.48357,2015
3,4,Norway,7.522,1.45900,1.33095,0.88521,0.66973,0.34699,0.36503,2015
4,5,Canada,7.427,1.32629,1.32261,0.90563,0.63297,0.45811,0.32957,2015

In [49]:
#  Merging multi-year datasets together
individual_datasets = [csv_2015_restructured,
                       csv_2016_restructured,
                       csv_2017_restructured,
                       csv_2018_restructured,
                       csv_2019_restructured]

combined_data = pd.concat(individual_datasets)
combined_data.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Year
0,1,Switzerland,7.587,1.39651,1.34951,0.94143,0.66557,0.29678,0.41978,2015
1,2,Iceland,7.561,1.30232,1.40223,0.94784,0.62877,0.43630,0.14145,2015
2,3,Denmark,7.527,1.32548,1.36058,0.87464,0.64938,0.34139,0.48357,2015
3,4,Norway,7.522,1.45900,1.33095,0.88521,0.66973,0.34699,0.36503,2015
4,5,Canada,7.427,1.32629,1.32261,0.90563,0.63297,0.45811,0.32957,2015

In [50]:
# Export to review in Excel
# combined_data.to_csv(r'C:\Users\simon\OneDrive\Desktop\combined_data.csv', index = False)